development:
  adapter: postgresql
  host: ec2-23-20-124-77.compute-1.amazonaws.com
  encoding: unicode
  database: da0d976jm8hh5m
  pool:     5
  username: prvrhdqfnrinbo
  password: e2a4c11be01bca3c8df5429c77c314441d5f99845ed16d7ae0949c769cf3b125
  template: template0